### ISSUE TITLE
VM is created at each reconciling

### ISSUE THREAD

**Issue by themoriarti** [alperencelik/kubemox#29]
Create a virtual machine from template by cloning. New virtual machine with the same name and a different id is created once a minute with each reconcile. After starting VM manualy, the creation of new ones stops.

This can be caused by different names and an incorrectly created virtual machine.

But it is very desirable that the newly created VM be registered by ID because it is unique, but the name is not unique.

Example:
```
apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachine
metadata:
  name: vm-new1
spec:
  name: vm-new-other1
  # Name of the node where the VM will be created
  nodeName: proxmox1
  template:
    # Name of the template to be cloned
    name: ubuntu-20
    # CPU cores to be allocated to the VM
    cores: 2
    # CPU sockets to be allocated to the VM
    socket: 1
    # Memory to be allocated to the VM
    memory: 4096 # As MB
    # Disk used by the VM
    disk: 
      - storage: kvm-disks
        size: 20 # As GB
        type: scsi
    # Network interfaces used by the VM
    network:
      - model: virtio
        bridge: vmbr0
```
